#基础配置，语言模型，词向量等
path_root: ""
#bert
vocab_file_path: "language_model/chinese_L-12_H-768_A-12/vocab.txt"
bert_config_file_path: "language_model/chinese_L-12_H-768_A-12/bert_config.json"
init_checkpoint_path: "language_model/chinese_L-12_H-768_A-12/bert_model.ckpt"
#elmo
init_checkpoint_path: "language_model/bilm_tf/data/checkpoint/model.ckpt-72848"
elmo_options_path: "language_model/bilm_tf/data/checkpoint/options.json"
elmo_vocab_path: "language_model/bilm_tf/data/vocab.txt"
#embedding
word_embedding_path: "data/baike_26g_news_13g_novel_229g.bin.sub"
char_embedding_path: "data/sgns.weibo.char.sub"
subword_embedding_path: "data/xxx"


