############### path ############
# path_root: "/content/data/classify/"
path_root: "data/classify/"
ori_path: "intent.csv"
# ori_path: "review.csv"
classes_path: "{encoder_type}classes"
dict_path: "{encoder_type}/dict.pkl"
checkpoint_path: "{encoder_type}/checkpoint"
model_path: "{encoder_type}/model.pb"
label_path: "{encoder_type}/label"
tfrecords_mode: "class"
tfrecords_path: "{encoder_type}/tfrecords"
export_dir_path: "{encoder_type}/model"


############ embedding ################
# embedding_type: char_embedding, word_embedding, subword_embedding
embedding_type: 'char_embedding'
embedding_size: 128
rand_embedding: True
use_language_model: False

############# clr #####################
use_clr: False
clr_mode: 'triangular'
max_learning_rate: 0.00005
step_size: 500

############# optim ###################
optimizer_type: "Adam"
loss_type: "softmax_loss"
learning_rate: 0.001

############# data ####################
maxlen: 20
batch_size: 64
num_class_per_batch: 16
test_size: 1
max_steps: 3000

# loss_type: "am_softmax_loss"

############ model ##############
config_type: 8
config: 
  0: {encoder_type: "fasttext", learning_rate: 0.003}
  1: {encoder_type: "transformer", learning_rate: 0.0001}
  2: {encoder_type: "transformer", embedding_type: 'subword_embedding', learning_rate: 0.0001}
  3: {encoder_type: "rnn", rnn_type: "gru", embedding_type: 'char_embedding', learning_rate: 0.001}
  4: {encoder_type: "rnn", rnn_type: "lstm", embedding_type: 'char_embedding', learning_rate: 0.001}
  5: {encoder_type: "attention_rnn", rnn_type: "gru", embedding_type: 'char_embedding', learning_rate: 0.001}
  6: {encoder_type: "rcnn", rnn_type: "gru", embedding_type: 'char_embedding', learning_rate: 0.001}
  7: {encoder_type: "capsule", caps_type: "A", embedding_type: 'char_embedding', learning_rate: 0.001, loss_type: "margin_loss"}
  8: {encoder_type: "bert", learning_rate: 0.00002, use_language_model: True, valid_step: 400,
      base_learning_rate: 0.000001}
  # 9: {encoder_type: "leaf", learning_rate: 0.003}

mode: "train"  #train\test\test_one
#mode: "test"  #train\test\test_one
#mode: "test_one"
# mode: "predict"
