############### path ############
path_root: "/content/data/match/"
path_root: "data/match/"
ori_path: "intent.csv"
# ori_path: "atec.csv"
no_train_path: "no_train.csv"
index_path: "index.csv"
relation_path: "relation.csv"
test_path: "test.csv"
classes_path: "{encoder_type}classes"
dict_path: "{encoder_type}/dict.pkl"
checkpoint_path: "{encoder_type}/checkpoint"
model_path: "{encoder_type}/model.pb"
label_path: "{encoder_type}/label"
cache_vec_path: "{encoder_type}/cache.vec.pkl"
tfrecords_path: "{encoder_type}/tfrecords"
export_dir_path: "{encoder_type}/model"


########### embedding ###########
#embedding_type: "word_embedding"
#embedding_size: 128
embedding_type: "char_embedding"
embedding_size: 300
rand_embedding: False
use_language_model: False

############# optim #############
learning_rate: 0.00001
optimizer_type: "Adam"
loss_type: "hinge_loss"
loss_type: "improved_triplet_loss"
# loss_type: "l2_loss"
is_distance: False
margin: 0.8

############# clr ###############
use_clr: True
max_learning_rate: 0.0005
step_size: 1000
clr_mode: 'triangular2'

############ data ###############
#class/89   pair/2
tfrecords_mode: "class"
maxlen: 20
max_steps: 3000
batch_size: 128
test_size: 1
score_thre: 0.65


############ model ##############
# sim_mode=cross: 对于交互的匹配方法
# sim_mode=represent: 基于表示的匹配方法
config_type: 10
config: 
  0: {encoder_type: "match_pyramid", sim_mode: "cross", num_output: 2, 
    learning_rate: 0.0005, tfrecords_mode: "pair", loss_type: "hinge_loss"}
  1: {encoder_type: "abcnn", sim_mode: "cross", num_output: 2, 
    learning_rate: 0.0005, tfrecords_mode: "pair", loss_type: "hinge_loss"}
  2: {encoder_type: "esim", sim_mode: "cross", num_output: 2, 
    learning_rate: 0.0001, tfrecords_mode: "pair", loss_type: "hinge_loss"}

  10: {encoder_type: "fasttext", sim_mode: "represent", num_output: 256, learning_rate: 0.00001}
  11: {encoder_type: "rnn", rnn_type: "gru", sim_mode: "represent", num_output: 256, learning_rate: 0.001}
  12: {encoder_type: "rnn", rnn_type: "lstm", sim_mode: "represent", num_output: 128, learning_rate: 0.001}
  13: {encoder_type: "rcnn", rnn_type: "lstm", sim_mode: "represent", num_output: 128, learning_rate: 0.001}
  14: {encoder_type: "attention_rnn", rnn_type: "gru", sim_mode: "represent", num_output: 128, learning_rate: 0.001}
  15: {encoder_type: "attention_rnn", rnn_type: "lstm", sim_mode: "represent", num_output: 128, learning_rate: 0.001}
  21: {encoder_type: "text_cnn", sim_mode: "represent", num_output: 256, learning_rate: 0.0001}
  22: {encoder_type: "transformer", sim_mode: "represent", num_output: 256, 
    learning_rate: 0.00001, embedding_size: 128, rand_embedding: True}
  23: {encoder_type: "bert", sim_mode: "represent", tfrecords_mode: "class", 
    learning_rate: 0.000001, use_language_model: True, num_output: 256,
    base_learning_rate: 0.000001}

  30: {encoder_type: "abcnn", sim_mode: "cross", num_output: 1, 
    learning_rate: 0.00005, tfrecords_mode: "point", loss_type: "sigmoid_loss", 
    test_size: 0.1, score_thre: 0.5}
  31: {encoder_type: "transformer", sim_mode: "represent", num_output: 256, 
    learning_rate: 0.00005, tfrecords_mode: "point", loss_type: "sigmoid_loss",
    embedding_size: 128, rand_embedding: True, test_size: 0.1, 
    score_thre: 0.5}
  32: {encoder_type: "bert", sim_mode: "cross", num_output: 1, 
    learning_rate: 0.00005, base_learning_rate: 0.000001,
    tfrecords_mode: "point", loss_type: "sigmoid_loss",
    test_size: 0.1, score_thre: 0.5, use_language_model: True}

mode: "train"  #train\test\test_one
#mode: "test"  #train\test\test_one
#mode: "test_one"  #train\test\test_one
