path_root: "data/translation/"
train_path: "turing"
dict_path: "vocab.pkl"

checkpoint_path: "checkpoint"
model_path: "model.pb"
use_language_model: False

maxlen: 40
embedding_size: 128
learning_rate: 0.001
batch_size: 64
num_epochs: 350
valid_step: 1000 #valid one time every valid_step 
# embedding_type: char_embedding, word_embedding, subword_embedding
embedding_type: 'char_embedding'
embedding_type: 'region_embedding'
rand_embedding: True

num_hidden: 128
num_layers: 1
#for translation, encoder_type only support "seq2seq" up to now
config_type: 1
config: 
  0: {encoder_type: "seq2seq", rnn_type: 'gru', embedding_type: 'char_embedding', learning_rate: 0.005}
  1: {encoder_type: "seq2seq", rnn_type: 'bi_lstm', embedding_type: 'char_embedding', learning_rate: 0.005}

mode: "train"  #train\test\test_one
#mode: "test_one"  #train\test\test_one


